### ISSUE TITLE
Likelihood function

### ISSUE THREAD

**Issue by yhl48** [tonyduan/mixture-density-network#5]
https://github.com/tonyduan/mixture-density-network/blob/5aa454dcee9841f94f622209248d0e2fbd8f2f50/src/blocks.py#L81

I was wondering if this is actually correct? Looks like you are summing the features before squaring the sums while it should be the other way around?

Correct me if I am wrong, but I believe it should be

```
torch.sum(z_score ** 2, dim=-1)

# or

torch.einsum("bij, bij -> bi", z_score, z_score) 
```

**Comment by tonyduan** [comment]
@yhl48 These expressions are identical. 

```
>>> z_score = torch.randn((5, 4, 2))
>>> z_score.shape
torch.Size([5, 4, 2])
>>> torch.einsum("bij, bij -> bi", z_score, z_score)
tensor([[1.7701, 3.7910, 0.9304, 0.3704],
        [1.3750, 0.0466, 0.0380, 1.6997],
        [2.9631, 0.0957, 1.4743, 0.7393],
        [1.2163, 1.1858, 0.5606, 1.7350],
        [0.7870, 1.5780, 0.9863, 0.2791]])
>>> torch.sum(z_score ** 2, dim=-1)
tensor([[1.7701, 3.7910, 0.9304, 0.3704],
        [1.3750, 0.0466, 0.0380, 1.6997],
        [2.9631, 0.0957, 1.4743, 0.7393],
        [1.2163, 1.1858, 0.5606, 1.7350],
        [0.7870, 1.5780, 0.9863, 0.2791]])
```

**Comment by yhl48** [comment]
@tonyduan yes those expressions are identical, but different from

`torch.einsum("bij, bik -> bi", z_score, z_score)`

**Comment by tonyduan** [comment]
@yhl48 Ah yes you're right, my apologies. Pushed a fix thank you.
