### ISSUE TITLE
Regressing multivariate response

### ISSUE THREAD

**Issue by ataey** [tonyduan/mixture-density-network#6]
Hi,

I would like to use this model to regress a multivariate response variable, but the output of `sample()` is not of the expected response variable size. For example, with `model = MixtureDensityNetwork(dim_in, dim_out, n_components, hidden_dim)`, where `dim_out > 1`, returns a variable of size `B x 1` instead of `B x out_dim` when using `sample()`. I would appreciate your advice if I am misunderstanding something.

**Comment by tonyduan** [comment]
Good find, thanks for catching. 

Pushed a bugfix in 5bfeae42de2adf42d680bdfee24bb8c2ce52f259. 

Let me know if this doesn't fix your issue.
